---
title: ezspacecss bootstrap utility classes
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: ezspacecss@gmail.com
author: David Manzer
url: http://www.ezspacecss.com
repo: https://github.com/dmanzer2/ez-space-css-repo
description: Bootstrap utility classes for quickly adding padding and margin spacing. Ideal for Boostrap 3 media queries
keywords: css margin and padding helper, bootstrap 3 utility, bootstrap 3 classes, utility classes, bootstrap 3 tool, margin css, padding css, margin classes, padding classes, margin, padding, sass, bower, css, bootstrap designer, bootstrap spacing, responsive classes, bootstrap design tool, css clases
color:
  primary-dark: "#111111"
  links: "#68DBE7"
footer: ez-space 1.1.0
social:
- title: stack-overflow
  url: http://stackoverflow.com/users/3818125/dmanzer2
- title: github
  url: https://github.com/dmanzer2/ez-space-css-repo
markdown: kramdown
permalink: pretty
