# Site settings
title: ez-space
email: dmanzer2@gmail.com
url: https://dmanzer2.github.io/jekyll-site/
description: "Simple css class system for quickly and easily adding space to your site."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#6ADDE6'

# Footer settings
footer: ez-space

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: stack-overflow
    url: http://stackoverflow.com/users/3818125/dmanzer2
  - title: github
    url: https://dmanzer2.github.io/ez-space/

# Build settings
markdown: kramdown
permalink: pretty
