---
title: ez-space
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: dmanzer2@gmail.com
url: https://dmanzer2.github.io/jekyll-site/
description: Simple css class system for quickly and easily adding space to your site.
color:
  primary-dark: "#000000"
  links: "#68DBE7"
footer: ez-space 1.0.0
social:
- title: stack-overflow
  url: http://stackoverflow.com/users/3818125/dmanzer2
- title: github
  url: https://dmanzer2.github.io/ez-space/
markdown: kramdown
permalink: pretty
